### ISSUE TITLE
Tutorial PDFs not rendered fully correctly

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Release-Support#3]
In the tutorial download, part 2 has some rendering issues. E.g., in section 7.3 (page 87) the red box callouts pointing to the rule are all blank. Looking at the original word docs it looks fine.

I haven't looked at the other parts of the tutorial to see how widespread this is.

![image](https://user-images.githubusercontent.com/535004/98855072-6e6f9e80-2429-11eb-8bd5-ae5b96ce4368.png)

**Comment by mazina** [comment]
If I recall correctly, we were never able to find a way to export those
word documents to pdf properly with the tools we had available at the time.
I thing we tried free utilities, Adobe distiller and word’s export, and
each had issues. I think exporting from Word, which ended up having the fewest
artifacts.

In any cae , John has been updating the tutorial recently, so we’ll be
creating a new version when he’s done. Hopefully, we’ll be able to get
better results.
