### ISSUE TITLE
convert current PDF content to HTML and host online

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Release-Support#9]
Would be really nice for discoverability, and I think also usability, to have all of the tutorials as well as the manual in HTML form hosted next to the API documentation and everything else we have for Soar.

**Comment by Bryan-Stearns** [comment]
I second this! ^^ A simple web portal with up-to-date info would be very useful for us at Optum.

**Comment by moschmdt** [comment]
I also support this!

My suggestion would be to use the Markdown based wiki of the official Soar GitHub repository via a mirror of a documentation repository.

In my opinion that could also have more positive side effects:

- Searching the GitHub Soar repository also shows results from the documentation.
- The last chapter of the manual (command index) is in the Soar GitHub repository
- Remove multiple locations of documentation
    - Soar Homepage with some blog articles
    - Manual
    - Tutorials
    - Wiki
- Linking between tutorials and the manual to reduce redundant documentation thus improving the learning journey for people who do not have a Soar expert at their disposal

**Comment by garfieldnate** [comment]
There are plenty of tools for converting markdown into static websites; I'd probably go with MkDocs, which is in Python and fairly straightforward. I think I'd prefer to work off of markdown documents that are simply in a git repo (perhaps in the Soar repo), with a GH Action that publishes to GH Pages, rather than relying on the GitHub wiki for now, as it's a bit more independent of the platform, and the manual and tutorial documents are important artifacts. I'd probably use the Wiki for information about developing the project itself, though (roadmap, etc.). What are your thoughts here?

Generating the API documentation is sort of another topic, but having a static website would give us a place to put this as well. Moving the Soar homepage would be another project as well, but it might be worth it, considering the relative difficulty with managing the current one.

**Comment by moschmdt** [comment]
I think that sounds reasonable from a user perspective to split the user and developer documentation. 

Generating the API documentation is another topic indeed, maybe that should be discussed in a separate issue to determine if there is even enough demand for it.

**Comment by garfieldnate** [comment]
This has been done quite well (thank you Moritz!). For follow-up tasks, we have opened separate tickets.
